# Generated by Django 4.2.17 on 2025-04-08 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_postlike_unique_together_postlike_like_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='like_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user', 'like_type')},
        ),
    ]
